# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: definitions.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class File(betterproto.Message):
    type: str = betterproto.string_field(1)
    id: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    size: int = betterproto.int64_field(4)
    hash: str = betterproto.string_field(5)
