# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tasks.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Text2imageRequest(betterproto.Message):
    prompt: str = betterproto.string_field(1)
    n: int = betterproto.int32_field(2)
    size: str = betterproto.string_field(3)


@dataclass
class Text2textRequest(betterproto.Message):
    messages: List[str] = betterproto.string_field(1)
    max_tokens: int = betterproto.int32_field(2)


@dataclass
class Text2audioRequest(betterproto.Message):
    prompt: str = betterproto.string_field(1)
    duration: int = betterproto.int32_field(2)
    steps: int = betterproto.int32_field(3)
    cfg_scale: float = betterproto.float_field(4)


@dataclass
class Text2imageResponse(betterproto.Message):
    result: str = betterproto.string_field(1)


@dataclass
class Text2textResponse(betterproto.Message):
    result: str = betterproto.string_field(1)


@dataclass
class Text2audioResponse(betterproto.Message):
    result: str = betterproto.string_field(1)


@dataclass
class TaskRequest(betterproto.Message):
    text2image: "Text2imageRequest" = betterproto.message_field(1, group="task")
    text2text: "Text2textRequest" = betterproto.message_field(2, group="task")
    text2audio: "Text2audioRequest" = betterproto.message_field(3, group="task")


@dataclass
class TaskResponse(betterproto.Message):
    text2image: "Text2imageResponse" = betterproto.message_field(1, group="response")
    text2text: "Text2textResponse" = betterproto.message_field(2, group="response")
    text2audio: "Text2audioResponse" = betterproto.message_field(3, group="response")
